Add the number of requested IPUs to attach error
Summary:
A customer has requested that the number of IPUs is made clearer when
we fail to attach to the IPU.

```
Could not find an available device for TensorFlow virtual device /device:IPU:<ordinal>. This device was expected to have N IPU(s). (... existing reasons)
```

Customer request: T51658 (ZD: normal)
Follows up on the easy bit of: T51792

There might be some more we can do for distributed systems but it becomes difficult to understand where that should be handled.

Full message is now:
```
tensorflow.python.framework.errors_impl.InternalError: Could not find an available device for TensorFlow virtual device /device:IPU:0. This device was expected to have 64 IPU(s). Common causes of this error include: incorrect configuration of your V-IPU partition, requesting more IPUs than are available on your system, or IPUs being used by another program. Use `gc-info -l` and `gc-monitor` to check your configuration.
```

TF1.15 Only

Test Plan: CI, tested locally

Reviewers: #tensorflow, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, markf

Reviewed By: #tensorflow, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, markf

Subscribers: markf

Maniphest Tasks: T51792, T52566

Differential Revision: https://phabricator.sourcevertex.net/D58855