Pass device ordinal to outfeed dequeue
Summary: Fixes T21202 where outfeeds couldn't be placed on any ordinal apart from 0

Test Plan:
Created a test but can't get it to run:

```
tensorflow.python.framework.errors_impl.FailedPreconditionError: No device target has been configured. Did you configure the IPU devices by running `tensorflow.python.ipu.configure_ipu_system(ipu_options)`?

```

Is it because IPU model doesn't support multiple IPUs?  Some other existing tests fail with this too when building with:

```
.linters/bazel test --test_env='TF_POPLAR_FLAGS=--use_ipu_model' --verbose_failures --test_output=all --config=opt tensorflow/python/ipu:infeed_outfeed_test
```

Reviewers: #tensorflow, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, georgep

Reviewed By: #tensorflow, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, georgep

Subscribers: hakons, georgep

Tags: #supportandengrequests

Maniphest Tasks: T21202

Differential Revision: https://phabricator.sourcevertex.net/D26667