fixed incorrect error message for keras model.py
Summary:
the _validate_dataset_element_count function has its numbers the wrong way around in the error message.
For example, predict() needs only one element, but if you give it 3 elements you get this error:
ValueError: predict requires a dataset with a structure containing 3 element(s), but got 1 element(s) instead.

TF2.1 only

Test Plan: /

Reviewers: #tensorflow, simonl, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, georgep

Reviewed By: #tensorflow, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, georgep

Subscribers: georgep, scottg

Maniphest Tasks: T36708

Differential Revision: https://phabricator.sourcevertex.net/D43486