Fix TensorFlow on Python 3.8 logger issue
This fix tries to address the issue raised in 33799
where running tensorflow on python 3.8 (Ubuntu 18.04)
raised the following error:
```
TypeError: _logger_find_caller() takes from 0 to 1 positional arguments but 2 were given
```

The issue was that findCaller changed in Python 3.8

This PR fixes the issue.

This PR fixes 33799

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>