Improved error message: verify that "distributed_batch_norm_replica_group_size" divides replication factor.
Summary:
T57992 This is an improved error handling for the case where the option `norms.experimental.distributed_batch_norm_replica_group_size` is set wrong.

Current situation:
- If the user set `distributed_batch_norm_replica_group_size` >`number of replicas`,
the error thrown is:
```
tensorflow.python.framework.errors_impl.UnknownError: GCL0224: replicaGroupStride = X with replicaGroupSize = Y is not valid for replication factor X
         [[{{node cluster}}]]
```
- Also if `distributed_batch_norm_replica_group_size` is smaller but doesn't divide the replication factor, the error thrown is currently:
```
tensorflow.python.framework.errors_impl.InternalError: [Poplar][Build graph] graph_replication_error: tensorflow/compiler/plugin/poplar/driver/ops/ops_helper.cc:67 replicaMap value (destination replica) X does not specify a valid replica (must be < replicationFactor=X)
         [[{{node cluster}}]]
```
Which doesn't really help to fix it.

The new error message would handle these two invalid cases.

TF1.15 Only

Reviewers: #tensorflow, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, gauthamg

Reviewed By: #tensorflow, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, gauthamg

Subscribers: gauthamg

Maniphest Tasks: T57992

Differential Revision: https://phabricator.sourcevertex.net/D73331