optimizer_v2: Improve error when called in cross-replica context
Summary:
When calling `Optimizer.apply_gradients()` in a cross-replica distribution context
(with a non-default distribution strategy), `distribute_ctx.get_replica_context()`
returns `None`, so it would fail with the error

    [...]/optimizer_v2.py", line 448, in apply_gradients
        return distribute_ctx.get_replica_context().merge_call(
    AttributeError: 'NoneType' object has no attribute 'merge_call'

This commit changes the error to a `RuntimeError` with a more descriptive error
message guiding the user towards `tf.distribute.Strategy.experimental_run_v2`.

Accepted upstream (but not merged yet): https://github.com/tensorflow/tensorflow/pull/36955

Reviewers: #tensorflow, #framework_ip_reviewer_-_no_oss_or_third-party_code_present._should_they_be_included_license_requirements_are_met, georgep

Reviewed By: #tensorflow, #framework_ip_reviewer_-_no_oss_or_third-party_code_present._should_they_be_included_license_requirements_are_met, georgep

Maniphest Tasks: T15742

Differential Revision: https://phabricator.sourcevertex.net/D21687