ipu_multi_worker_strategy: Fix initializer colocation
Summary:
This `_class` attribute should apparently be a list, otherwise
`Operation.colocation_groups()` blows up with

  AttributeError: 'int' object has no attribute 'startswith'

because it's iterating over the bytes, rather than the list items.

This issue has been seen with the IPUMultiReplicaStrategy
(which inherits from this one) in the CNN public example
with autosharding enabled (deprecated, I know).

Fixes T32698.

Test Plan:
Added test that failed before, but passes now.
poprun in public_examples with autosharding now works.

Reviewers: #tensorflow, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, markf, georgep

Reviewed By: #tensorflow, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, markf, georgep

Maniphest Tasks: T32698

Differential Revision: https://phabricator.sourcevertex.net/D38791