host_embedding_lookup_test: Use a non-resource variable in TF2
Summary:
Fixes the following error in r2.1:

    TypeError: 'IpuHostEmbedding' Op requires that input 'ref' be a
    mutable tensor but was ['tf.float32'] (e.g.: a tf.Variable)

Reviewers: #tensorflow, jakeh

Reviewed By: #tensorflow, jakeh

Differential Revision: https://phabricator.sourcevertex.net/D20906