Make sure that `_get_last_batch_results` takes local replication factor into account
Summary:
TF2.4 Only

Currently `_get_last_batch_results` only takes the global replication factor into account to see whether the result from the outfeed queue should be mapped multiple times. This is incorrect in the case where you use popdist with two instances with each 1 replica. Your local replication factor is 1 here, but the global replication factor is 2. This causes:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Index out of range using input dim 0; input has only 0 dims [Op:StridedSlice] name: strided_slice/
```

Reviewers: #tensorflow, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, georgep

Reviewed By: #tensorflow, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, georgep

Subscribers: harrym, georgep

Maniphest Tasks: T45986, T49733

Differential Revision: https://phabricator.sourcevertex.net/D55336